version: '3'

services:
  backendgo:
    build: ./backend-go
    restart: always
    ports: 
      - 3001:3001
  backend:
    build: ./backend
    restart: always
    ports:
      - 5001:5001
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
  bdd:
    image: neo4j:latest
    restart: always
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      NEO4J_AUTH: neo4j/Saucisse02
    volumes:
      - ./bdd:/data
