#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff --name-only --cached --diff-filter=d | grep -E '.(ts|json|js|svelte)$' | xargs -r prettier --write && git diff --name-only --cached --diff-filter=d | grep -E '.(ts|json|js|svelte)$' | xargs -r git add
