name: Build images docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env: 
  REGISTRY: ghrc.io

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - # checkout
        name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - # Extract metadata
          name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/backend
      - # build the container image and push it to Docker \
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: ./backend-go/
            file: ./backend-go/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
