name: Build images docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./backend-go/Dockerfile
            context: ./backend-go/
            image: ghcr.io/Nuxnuxx/backend
          - dockerfile: ./frontend/Dockerfile
            context: ./frontend/
            image: ghcr.io/Nuxnuxx/frontend

    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - # checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - # Extract metadata
          name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ matrix.image}}

      - # build the container image and push it to Docker \
          name: Build and push backend
          uses: docker/build-push-action@v5
          with:
            context: ${{ matrix.context}}
            file: ${{ matrix.dockerfile}}
            push: ${{ github.event_name != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
