name: Build and push images

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
          
      - name: Build image
        run: docker compose -f docker-compose.prod.yml build

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        
      - name: Push image to Container Registry
        if: github.event_name != 'pull_request'
        run: docker compose -f docker-compose.prod.yml push
