name: Deploy through SSH
on: [push, pull_request, workflow_dispatch]
jobs:
  deploy_on_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}

      - name: Executing remote ssh commands using keys
        run:
          mkdir -p ~/.ssh/
          echo "$key" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $host
            User $username
            Port $port
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa <<< "$passphrase"; ssh -p $port $username@$host "whoami"'
        env:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
