name: Deploy

on:
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  name: Deploy on server
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
    - name: Connect to VPN
      uses: "kota65535/github-openvpn-connect-action@v2"
      with:
        config_file: .github/workflows/client.ovpn
        username: ${{ secrets.OVPN_USERNAME }}
        password: ${{ secrets.OVPN_PASSWORD }}
        client_key: ${{ secrets.USER_KEY }}
    - name: executing remote ssh commands using keys
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{secrets.SSH_USERNAME }}
        key: ${{ secrest.SSH_KEY }}
        port: ${{ secrests.SSH_PORT }}
        script: whoami
