name: Prettier Code Formatting

on:
  push:
    branches:
      - main

jobs:
  prettier-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Run Prettier On Backend
        run: |
            cd backend
            npm install
            npx prettier --write .

      - name: Install dependencies
        run: |
            cd frontend
            npm install
            npx prettier --write .
