name: Prettier Code Formatting

on:
  pull_request:

jobs:
  prettier-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: run prettier on backend
        run: |
            cd backend
            npm i
            npm run format

      - name: run prettier on Frontend
        run: |
            cd frontend
            npm i
            npm run format
