name: Add Pull Request to Project

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: web-SAE
          column-name: Todo
          issue-number: ${{ github.event.number }}
