name: Run unit test

on:
  pull_request:

jobs:
  build:
    name: Analysis code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: run unit test on frontend
        run: |
            cd backend
            npm run test

      - name: run unit test on backend
        run: |
            cd frontend
            npm run test
